# Header
menu:
  Home: /
  Archives: /archives

# URL basename of the main cover image. Make sure you deliver three files:
# <index_cover>@preview.gif, <index_cover>.jpg and <index_cover>@2x.jpg.
index_cover: /img/home-bg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url:
github_url: https://github.com/klugjo/hexo-theme-clean-blog
